//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalesRunnerForm.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TalesRunnerForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1024_gameu_2 {
            get {
                object obj = ResourceManager.GetObject("_1024_gameu_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1024_gameu_3 {
            get {
                object obj = ResourceManager.GetObject("_1024_gameu_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1024_gameu_l {
            get {
                object obj = ResourceManager.GetObject("_1024_gameu_l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1024_gameu_r {
            get {
                object obj = ResourceManager.GetObject("_1024_gameu_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Made by Yuki, FlyBalloon
        ///本工具仅用于查看TalesRunner的装备属性
        ///
        ///工具版本：2.6.2
        ///装备库版本： 的本地化字符串。
        /// </summary>
        internal static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///本次更新：
        ///露露亚角色更新
        ///箱子名称黑名单的自定义化，通过点击箱子页的黑名单即可（测试）
        ///鱼饵道具加入开箱页面
        ///修复开箱页面，最后一页最后一个箱子不显示的现象
        ///
        ///未来更新：
        ///联网的版本更新（也不知道还能有几个版本）
        ///提供英化韩化配置文件
        ///
        ///注1：
        ///出于方便玩家翻译的理由,本工具的档案没有加密
        ///可以自行修改(但是记得备份)
        ///
        ///注2：
        ///搜索属性第三项改为自定义数值
        ///方便各位使用者查找一些特殊的属性
        ///详细编号可查阅[ID]选项卡 的本地化字符串。
        /// </summary>
        internal static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap all_char {
            get {
                object obj = ResourceManager.GetObject("all_char", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 1.5倍 的本地化字符串。
        /// </summary>
        internal static string Anubis_15 {
            get {
                return ResourceManager.GetString("Anubis_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暴击 的本地化字符串。
        /// </summary>
        internal static string Anubis_Crit {
            get {
                return ResourceManager.GetString("Anubis_Crit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伤害 的本地化字符串。
        /// </summary>
        internal static string Anubis_Damage {
            get {
                return ResourceManager.GetString("Anubis_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 愤怒 的本地化字符串。
        /// </summary>
        internal static string Anubis_Fury {
            get {
                return ResourceManager.GetString("Anubis_Fury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通 的本地化字符串。
        /// </summary>
        internal static string Anubis_Normal {
            get {
                return ResourceManager.GetString("Anubis_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性总和  的本地化字符串。
        /// </summary>
        internal static string Anubis_StatusAddUp {
            get {
                return ResourceManager.GetString("Anubis_StatusAddUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;在Avatar Off时套用属性&gt; 的本地化字符串。
        /// </summary>
        internal static string Attr_AvatarOff {
            get {
                return ResourceManager.GetString("Attr_AvatarOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;在Avatar On时套用属性&gt; 的本地化字符串。
        /// </summary>
        internal static string Attr_AvatarOn {
            get {
                return ResourceManager.GetString("Attr_AvatarOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 适用角色: 的本地化字符串。
        /// </summary>
        internal static string Attr_Character {
            get {
                return ResourceManager.GetString("Attr_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏等级: 的本地化字符串。
        /// </summary>
        internal static string Attr_CollectLv {
            get {
                return ResourceManager.GetString("Attr_CollectLv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏编号: 的本地化字符串。
        /// </summary>
        internal static string Attr_CollectNum {
            get {
                return ResourceManager.GetString("Attr_CollectNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏分数: 的本地化字符串。
        /// </summary>
        internal static string Attr_CollectPt {
            get {
                return ResourceManager.GetString("Attr_CollectPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装备编号: 的本地化字符串。
        /// </summary>
        internal static string Attr_ItemNum {
            get {
                return ResourceManager.GetString("Attr_ItemNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装备名称: 的本地化字符串。
        /// </summary>
        internal static string Attr_Name {
            get {
                return ResourceManager.GetString("Attr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文名称: 的本地化字符串。
        /// </summary>
        internal static string Attr_NameCH {
            get {
                return ResourceManager.GetString("Attr_NameCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装备部位: 的本地化字符串。
        /// </summary>
        internal static string Attr_Position {
            get {
                return ResourceManager.GetString("Attr_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套装编号: 的本地化字符串。
        /// </summary>
        internal static string Attr_SetNum {
            get {
                return ResourceManager.GetString("Attr_SetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套装所属 的本地化字符串。
        /// </summary>
        internal static string CardPackMap_Other {
            get {
                return ResourceManager.GetString("CardPackMap_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数学王系列 的本地化字符串。
        /// </summary>
        internal static string CardPackMap1 {
            get {
                return ResourceManager.GetString("CardPackMap1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彼得潘 的本地化字符串。
        /// </summary>
        internal static string CardPackMap10 {
            get {
                return ResourceManager.GetString("CardPackMap10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 青蛙王子 的本地化字符串。
        /// </summary>
        internal static string CardPackMap11 {
            get {
                return ResourceManager.GetString("CardPackMap11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被遗忘的天使神殿 的本地化字符串。
        /// </summary>
        internal static string CardPackMap2 {
            get {
                return ResourceManager.GetString("CardPackMap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亨利城的训练 的本地化字符串。
        /// </summary>
        internal static string CardPackMap3 {
            get {
                return ResourceManager.GetString("CardPackMap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阿里巴巴 的本地化字符串。
        /// </summary>
        internal static string CardPackMap4 {
            get {
                return ResourceManager.GetString("CardPackMap4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 四人同心 的本地化字符串。
        /// </summary>
        internal static string CardPackMap5 {
            get {
                return ResourceManager.GetString("CardPackMap5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地狱火之路 的本地化字符串。
        /// </summary>
        internal static string CardPackMap6 {
            get {
                return ResourceManager.GetString("CardPackMap6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冰河世纪 的本地化字符串。
        /// </summary>
        internal static string CardPackMap7 {
            get {
                return ResourceManager.GetString("CardPackMap7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 魔笛 的本地化字符串。
        /// </summary>
        internal static string CardPackMap8 {
            get {
                return ResourceManager.GetString("CardPackMap8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 甜蜜的饼干树林 的本地化字符串。
        /// </summary>
        internal static string CardPackMap9 {
            get {
                return ResourceManager.GetString("CardPackMap9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全体角色通用 的本地化字符串。
        /// </summary>
        internal static string Character_Other {
            get {
                return ResourceManager.GetString("Character_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光光 的本地化字符串。
        /// </summary>
        internal static string Character1 {
            get {
                return ResourceManager.GetString("Character1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凯 的本地化字符串。
        /// </summary>
        internal static string Character10 {
            get {
                return ResourceManager.GetString("Character10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雪 的本地化字符串。
        /// </summary>
        internal static string Character11 {
            get {
                return ResourceManager.GetString("Character11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深子 的本地化字符串。
        /// </summary>
        internal static string Character12 {
            get {
                return ResourceManager.GetString("Character12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亚伯 的本地化字符串。
        /// </summary>
        internal static string Character13 {
            get {
                return ResourceManager.GetString("Character13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哈鲁 的本地化字符串。
        /// </summary>
        internal static string Character14 {
            get {
                return ResourceManager.GetString("Character14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维拉 的本地化字符串。
        /// </summary>
        internal static string Character15 {
            get {
                return ResourceManager.GetString("Character15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孙悟空 的本地化字符串。
        /// </summary>
        internal static string Character16 {
            get {
                return ResourceManager.GetString("Character16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐雷 的本地化字符串。
        /// </summary>
        internal static string Character17 {
            get {
                return ResourceManager.GetString("Character17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曦狐 的本地化字符串。
        /// </summary>
        internal static string Character18 {
            get {
                return ResourceManager.GetString("Character18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 露西 的本地化字符串。
        /// </summary>
        internal static string Character19 {
            get {
                return ResourceManager.GetString("Character19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明明 的本地化字符串。
        /// </summary>
        internal static string Character2 {
            get {
                return ResourceManager.GetString("Character2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米狐 的本地化字符串。
        /// </summary>
        internal static string Character20 {
            get {
                return ResourceManager.GetString("Character20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GyuRi 的本地化字符串。
        /// </summary>
        internal static string Character201 {
            get {
                return ResourceManager.GetString("Character201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SeungYeon 的本地化字符串。
        /// </summary>
        internal static string Character202 {
            get {
                return ResourceManager.GetString("Character202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nicole 的本地化字符串。
        /// </summary>
        internal static string Character203 {
            get {
                return ResourceManager.GetString("Character203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hara 的本地化字符串。
        /// </summary>
        internal static string Character204 {
            get {
                return ResourceManager.GetString("Character204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ji-Young 的本地化字符串。
        /// </summary>
        internal static string Character205 {
            get {
                return ResourceManager.GetString("Character205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amu 的本地化字符串。
        /// </summary>
        internal static string Character206 {
            get {
                return ResourceManager.GetString("Character206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Giroro 的本地化字符串。
        /// </summary>
        internal static string Character207 {
            get {
                return ResourceManager.GetString("Character207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dororo 的本地化字符串。
        /// </summary>
        internal static string Character208 {
            get {
                return ResourceManager.GetString("Character208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keroro 的本地化字符串。
        /// </summary>
        internal static string Character209 {
            get {
                return ResourceManager.GetString("Character209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基纳莉 的本地化字符串。
        /// </summary>
        internal static string Character21 {
            get {
                return ResourceManager.GetString("Character21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tamama 的本地化字符串。
        /// </summary>
        internal static string Character210 {
            get {
                return ResourceManager.GetString("Character210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kururu 的本地化字符串。
        /// </summary>
        internal static string Character211 {
            get {
                return ResourceManager.GetString("Character211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min 的本地化字符串。
        /// </summary>
        internal static string Character212 {
            get {
                return ResourceManager.GetString("Character212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fei 的本地化字符串。
        /// </summary>
        internal static string Character213 {
            get {
                return ResourceManager.GetString("Character213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suzy 的本地化字符串。
        /// </summary>
        internal static string Character214 {
            get {
                return ResourceManager.GetString("Character214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jia 的本地化字符串。
        /// </summary>
        internal static string Character215 {
            get {
                return ResourceManager.GetString("Character215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZICO 的本地化字符串。
        /// </summary>
        internal static string Character216 {
            get {
                return ResourceManager.GetString("Character216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JAEHYO 的本地化字符串。
        /// </summary>
        internal static string Character217 {
            get {
                return ResourceManager.GetString("Character217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P.O 的本地化字符串。
        /// </summary>
        internal static string Character218 {
            get {
                return ResourceManager.GetString("Character218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 U-KWON 的本地化字符串。
        /// </summary>
        internal static string Character219 {
            get {
                return ResourceManager.GetString("Character219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R 的本地化字符串。
        /// </summary>
        internal static string Character22 {
            get {
                return ResourceManager.GetString("Character22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B-Bomb 的本地化字符串。
        /// </summary>
        internal static string Character220 {
            get {
                return ResourceManager.GetString("Character220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P-KYUNG 的本地化字符串。
        /// </summary>
        internal static string Character221 {
            get {
                return ResourceManager.GetString("Character221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TAEIL 的本地化字符串。
        /// </summary>
        internal static string Character222 {
            get {
                return ResourceManager.GetString("Character222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 哈朗 的本地化字符串。
        /// </summary>
        internal static string Character23 {
            get {
                return ResourceManager.GetString("Character23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拉拉 的本地化字符串。
        /// </summary>
        internal static string Character24 {
            get {
                return ResourceManager.GetString("Character24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 埃利姆斯 的本地化字符串。
        /// </summary>
        internal static string Character25 {
            get {
                return ResourceManager.GetString("Character25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凯恩 的本地化字符串。
        /// </summary>
        internal static string Character26 {
            get {
                return ResourceManager.GetString("Character26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缘迕 的本地化字符串。
        /// </summary>
        internal static string Character27 {
            get {
                return ResourceManager.GetString("Character27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 血腥维拉 的本地化字符串。
        /// </summary>
        internal static string Character28 {
            get {
                return ResourceManager.GetString("Character28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 莉娜 的本地化字符串。
        /// </summary>
        internal static string Character3 {
            get {
                return ResourceManager.GetString("Character3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大熊 的本地化字符串。
        /// </summary>
        internal static string Character4 {
            get {
                return ResourceManager.GetString("Character4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DnD 的本地化字符串。
        /// </summary>
        internal static string Character5 {
            get {
                return ResourceManager.GetString("Character5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纳鲁西斯 的本地化字符串。
        /// </summary>
        internal static string Character6 {
            get {
                return ResourceManager.GetString("Character6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 琪琪 的本地化字符串。
        /// </summary>
        internal static string Character7 {
            get {
                return ResourceManager.GetString("Character7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷 的本地化字符串。
        /// </summary>
        internal static string Character8 {
            get {
                return ResourceManager.GetString("Character8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贝儿 的本地化字符串。
        /// </summary>
        internal static string Character9 {
            get {
                return ResourceManager.GetString("Character9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外装 的本地化字符串。
        /// </summary>
        internal static string Collocation_Avatar {
            get {
                return ResourceManager.GetString("Collocation_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内装 的本地化字符串。
        /// </summary>
        internal static string Collocation_Character {
            get {
                return ResourceManager.GetString("Collocation_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] DevIL {
            get {
                object obj = ResourceManager.GetObject("DevIL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 装备名称 的本地化字符串。
        /// </summary>
        internal static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string Header_Num {
            get {
                return ResourceManager.GetString("Header_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ILU {
            get {
                object obj = ResourceManager.GetObject("ILU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 必须指定节点名称 的本地化字符串。
        /// </summary>
        internal static string IniOperation_IniGetAllItemKeys_必须指定节点名称 {
            get {
                return ResourceManager.GetString("IniOperation_IniGetAllItemKeys_必须指定节点名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须指定键名称(key) 的本地化字符串。
        /// </summary>
        internal static string IniOperation_IniGetStringValue_必须指定键名称_key_ {
            get {
                return ResourceManager.GetString("IniOperation_IniGetStringValue_必须指定键名称_key_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须指定键值对 的本地化字符串。
        /// </summary>
        internal static string IniOperation_IniWriteItems_必须指定键值对 {
            get {
                return ResourceManager.GetString("IniOperation_IniWriteItems_必须指定键值对", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为null 的本地化字符串。
        /// </summary>
        internal static string IniOperation_IniWriteValue_值不能为null {
            get {
                return ResourceManager.GetString("IniOperation_IniWriteValue_值不能为null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须指定键名称 的本地化字符串。
        /// </summary>
        internal static string IniOperation_IniWriteValue_必须指定键名称 {
            get {
                return ResourceManager.GetString("IniOperation_IniWriteValue_必须指定键名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1|100|TR +
        ///2|100|EXP +
        ///3|100|愤怒累计速度 +
        ///4|100|防电 +
        ///5|100|防踩 +
        ///7|100|愤怒持续时间 +
        ///8|100|防御攻击类道具概率 +
        ///9|100|幸运 +
        ///11|100|愤怒时把周围玩家变身的概率 +
        ///12|100|个人战房间中其他人都失败时TR +
        ///13|100|团队、接力比赛中房间其他队伍都失败时TR、EXP +
        ///14|100|个人赛中进前三名时TR、EXP +
        ///15|100|团队、接力赛中获胜时TR +
        ///16|1|游戏开始后|秒内无敌
        ///17|1|最高速度 +
        ///18|1|加速度 +
        ///19|1|力量 +
        ///20|1|控制 +
        ///21|100|被踩时发动冲刺的概率 +
        ///22|100|铁桶持续时间 -
        ///23|100|铁桶闪避几率 +
        ///24|100|团队、接力比赛中胜利时的EXP +
        ///25|1|愤怒时周围炸弹范围 +
        ///26|100|被踩时弹开踩人者的概率 +
        ///27|100|被踩时获得TR的概率 +
        ///28|1|被踩时 +|TR
        ///29|1|被踩时获得TR的次数 +|次
        ///30|1|个人赛随机TR奖励0%~|%
        ///31| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string itemattr {
            get {
                return ResourceManager.GetString("itemattr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap noImage {
            get {
                object obj = ResourceManager.GetObject("noImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string Page_About {
            get {
                return ResourceManager.GetString("Page_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        internal static string Page_Attr {
            get {
                return ResourceManager.GetString("Page_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配装 的本地化字符串。
        /// </summary>
        internal static string Page_Collocation {
            get {
                return ResourceManager.GetString("Page_Collocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string Page_ID {
            get {
                return ResourceManager.GetString("Page_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Page_Search {
            get {
                return ResourceManager.GetString("Page_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同 的本地化字符串。
        /// </summary>
        internal static string PetSeries_Other {
            get {
                return ResourceManager.GetString("PetSeries_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A型 的本地化字符串。
        /// </summary>
        internal static string PetSeries1 {
            get {
                return ResourceManager.GetString("PetSeries1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 神秘公寓 的本地化字符串。
        /// </summary>
        internal static string PetSeries10 {
            get {
                return ResourceManager.GetString("PetSeries10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天使 的本地化字符串。
        /// </summary>
        internal static string PetSeries11 {
            get {
                return ResourceManager.GetString("PetSeries11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恶魔 的本地化字符串。
        /// </summary>
        internal static string PetSeries12 {
            get {
                return ResourceManager.GetString("PetSeries12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 塔罗牌 的本地化字符串。
        /// </summary>
        internal static string PetSeries13 {
            get {
                return ResourceManager.GetString("PetSeries13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级跑跑角色 的本地化字符串。
        /// </summary>
        internal static string PetSeries14 {
            get {
                return ResourceManager.GetString("PetSeries14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国际象棋 的本地化字符串。
        /// </summary>
        internal static string PetSeries15 {
            get {
                return ResourceManager.GetString("PetSeries15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B型 的本地化字符串。
        /// </summary>
        internal static string PetSeries2 {
            get {
                return ResourceManager.GetString("PetSeries2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 O型 的本地化字符串。
        /// </summary>
        internal static string PetSeries3 {
            get {
                return ResourceManager.GetString("PetSeries3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AB型 的本地化字符串。
        /// </summary>
        internal static string PetSeries4 {
            get {
                return ResourceManager.GetString("PetSeries4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GirlsDay 的本地化字符串。
        /// </summary>
        internal static string PetSeries5 {
            get {
                return ResourceManager.GetString("PetSeries5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GirlFriend 的本地化字符串。
        /// </summary>
        internal static string PetSeries6 {
            get {
                return ResourceManager.GetString("PetSeries6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEVENTEEN 的本地化字符串。
        /// </summary>
        internal static string PetSeries7 {
            get {
                return ResourceManager.GetString("PetSeries7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BTS 的本地化字符串。
        /// </summary>
        internal static string PetSeries8 {
            get {
                return ResourceManager.GetString("PetSeries8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Astro 的本地化字符串。
        /// </summary>
        internal static string PetSeries9 {
            get {
                return ResourceManager.GetString("PetSeries9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string Position_1001 {
            get {
                return ResourceManager.GetString("Position_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变身 的本地化字符串。
        /// </summary>
        internal static string Position_1002 {
            get {
                return ResourceManager.GetString("Position_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊 的本地化字符串。
        /// </summary>
        internal static string Position_1003 {
            get {
                return ResourceManager.GetString("Position_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合作角色 的本地化字符串。
        /// </summary>
        internal static string Position_1004 {
            get {
                return ResourceManager.GetString("Position_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头发 的本地化字符串。
        /// </summary>
        internal static string Position_2001 {
            get {
                return ResourceManager.GetString("Position_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上衣 的本地化字符串。
        /// </summary>
        internal static string Position_2002 {
            get {
                return ResourceManager.GetString("Position_2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下衣 的本地化字符串。
        /// </summary>
        internal static string Position_2003 {
            get {
                return ResourceManager.GetString("Position_2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鞋子 的本地化字符串。
        /// </summary>
        internal static string Position_2004 {
            get {
                return ResourceManager.GetString("Position_2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头饰 的本地化字符串。
        /// </summary>
        internal static string Position_3001 {
            get {
                return ResourceManager.GetString("Position_3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面饰 的本地化字符串。
        /// </summary>
        internal static string Position_3002 {
            get {
                return ResourceManager.GetString("Position_3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颈饰 的本地化字符串。
        /// </summary>
        internal static string Position_3003 {
            get {
                return ResourceManager.GetString("Position_3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手饰 的本地化字符串。
        /// </summary>
        internal static string Position_3004 {
            get {
                return ResourceManager.GetString("Position_3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背饰 的本地化字符串。
        /// </summary>
        internal static string Position_3005 {
            get {
                return ResourceManager.GetString("Position_3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项链 的本地化字符串。
        /// </summary>
        internal static string Position_3007 {
            get {
                return ResourceManager.GetString("Position_3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手环 的本地化字符串。
        /// </summary>
        internal static string Position_3008 {
            get {
                return ResourceManager.GetString("Position_3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推进器 的本地化字符串。
        /// </summary>
        internal static string Position_3009 {
            get {
                return ResourceManager.GetString("Position_3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾巴 的本地化字符串。
        /// </summary>
        internal static string Position_3010 {
            get {
                return ResourceManager.GetString("Position_3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宠物 的本地化字符串。
        /// </summary>
        internal static string Position_4001 {
            get {
                return ResourceManager.GetString("Position_4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荣誉 的本地化字符串。
        /// </summary>
        internal static string Position_5006 {
            get {
                return ResourceManager.GetString("Position_5006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 象征 的本地化字符串。
        /// </summary>
        internal static string Position_5010 {
            get {
                return ResourceManager.GetString("Position_5010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        internal static string Position_Other {
            get {
                return ResourceManager.GetString("Position_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套装 的本地化字符串。
        /// </summary>
        internal static string Position_Set {
            get {
                return ResourceManager.GetString("Position_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position1001 {
            get {
                object obj = ResourceManager.GetObject("position1001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position1003 {
            get {
                object obj = ResourceManager.GetObject("position1003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position2001 {
            get {
                object obj = ResourceManager.GetObject("position2001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position2002 {
            get {
                object obj = ResourceManager.GetObject("position2002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position2003 {
            get {
                object obj = ResourceManager.GetObject("position2003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position2004 {
            get {
                object obj = ResourceManager.GetObject("position2004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3001 {
            get {
                object obj = ResourceManager.GetObject("position3001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3002 {
            get {
                object obj = ResourceManager.GetObject("position3002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3003 {
            get {
                object obj = ResourceManager.GetObject("position3003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3004 {
            get {
                object obj = ResourceManager.GetObject("position3004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3005 {
            get {
                object obj = ResourceManager.GetObject("position3005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3007 {
            get {
                object obj = ResourceManager.GetObject("position3007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3008 {
            get {
                object obj = ResourceManager.GetObject("position3008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3009 {
            get {
                object obj = ResourceManager.GetObject("position3009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position3010 {
            get {
                object obj = ResourceManager.GetObject("position3010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position4001 {
            get {
                object obj = ResourceManager.GetObject("position4001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position5006 {
            get {
                object obj = ResourceManager.GetObject("position5006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap position5010 {
            get {
                object obj = ResourceManager.GetObject("position5010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string Search_All {
            get {
                return ResourceManager.GetString("Search_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        internal static string Search_Ascending {
            get {
                return ResourceManager.GetString("Search_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内外装 的本地化字符串。
        /// </summary>
        internal static string Search_AvatarAll {
            get {
                return ResourceManager.GetString("Search_AvatarAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内装 的本地化字符串。
        /// </summary>
        internal static string Search_AvatarOff {
            get {
                return ResourceManager.GetString("Search_AvatarOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外装 的本地化字符串。
        /// </summary>
        internal static string Search_AvatarOn {
            get {
                return ResourceManager.GetString("Search_AvatarOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文(如果有) 的本地化字符串。
        /// </summary>
        internal static string Search_Chinese {
            get {
                return ResourceManager.GetString("Search_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏编号 的本地化字符串。
        /// </summary>
        internal static string Search_CollectNum {
            get {
                return ResourceManager.GetString("Search_CollectNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件搜索 的本地化字符串。
        /// </summary>
        internal static string Search_Condition {
            get {
                return ResourceManager.GetString("Search_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索条件1 的本地化字符串。
        /// </summary>
        internal static string Search_Condition1 {
            get {
                return ResourceManager.GetString("Search_Condition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索条件2 的本地化字符串。
        /// </summary>
        internal static string Search_Condition2 {
            get {
                return ResourceManager.GetString("Search_Condition2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索条件3 的本地化字符串。
        /// </summary>
        internal static string Search_Condition3 {
            get {
                return ResourceManager.GetString("Search_Condition3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        internal static string Search_Descending {
            get {
                return ResourceManager.GetString("Search_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装备编号 的本地化字符串。
        /// </summary>
        internal static string Search_ItemNum {
            get {
                return ResourceManager.GetString("Search_ItemNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位 的本地化字符串。
        /// </summary>
        internal static string Search_Jump {
            get {
                return ResourceManager.GetString("Search_Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韩文 的本地化字符串。
        /// </summary>
        internal static string Search_Korean {
            get {
                return ResourceManager.GetString("Search_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装备语言 的本地化字符串。
        /// </summary>
        internal static string Search_Language {
            get {
                return ResourceManager.GetString("Search_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装备定位 的本地化字符串。
        /// </summary>
        internal static string Search_Num {
            get {
                return ResourceManager.GetString("Search_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号排序 的本地化字符串。
        /// </summary>
        internal static string Search_NumSort {
            get {
                return ResourceManager.GetString("Search_NumSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部位 的本地化字符串。
        /// </summary>
        internal static string Search_Position {
            get {
                return ResourceManager.GetString("Search_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Search_Search {
            get {
                return ResourceManager.GetString("Search_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复全部 的本地化字符串。
        /// </summary>
        internal static string Search_ShowAll {
            get {
                return ResourceManager.GetString("Search_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女性角色通用 的本地化字符串。
        /// </summary>
        internal static string Sex_Female {
            get {
                return ResourceManager.GetString("Sex_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男性角色通用 的本地化字符串。
        /// </summary>
        internal static string Sex_Male {
            get {
                return ResourceManager.GetString("Sex_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全体角色通用 的本地化字符串。
        /// </summary>
        internal static string Sex_Other {
            get {
                return ResourceManager.GetString("Sex_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分角色通用 的本地化字符串。
        /// </summary>
        internal static string Sex_Part {
            get {
                return ResourceManager.GetString("Sex_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        internal static string Stone_A {
            get {
                return ResourceManager.GetString("Stone_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B 的本地化字符串。
        /// </summary>
        internal static string Stone_B {
            get {
                return ResourceManager.GetString("Stone_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝色宝石 的本地化字符串。
        /// </summary>
        internal static string Stone_Blue {
            get {
                return ResourceManager.GetString("Stone_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_blue_0 {
            get {
                object obj = ResourceManager.GetObject("stone_blue_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_blue_1 {
            get {
                object obj = ResourceManager.GetObject("stone_blue_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_blue_2 {
            get {
                object obj = ResourceManager.GetObject("stone_blue_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_blue_3 {
            get {
                object obj = ResourceManager.GetObject("stone_blue_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_blue_4 {
            get {
                object obj = ResourceManager.GetObject("stone_blue_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_blue_5 {
            get {
                object obj = ResourceManager.GetObject("stone_blue_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 C 的本地化字符串。
        /// </summary>
        internal static string Stone_C {
            get {
                return ResourceManager.GetString("Stone_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D 的本地化字符串。
        /// </summary>
        internal static string Stone_D {
            get {
                return ResourceManager.GetString("Stone_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E 的本地化字符串。
        /// </summary>
        internal static string Stone_E {
            get {
                return ResourceManager.GetString("Stone_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F 的本地化字符串。
        /// </summary>
        internal static string Stone_F {
            get {
                return ResourceManager.GetString("Stone_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 G 的本地化字符串。
        /// </summary>
        internal static string Stone_G {
            get {
                return ResourceManager.GetString("Stone_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿色宝石 的本地化字符串。
        /// </summary>
        internal static string Stone_Green {
            get {
                return ResourceManager.GetString("Stone_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_green_0 {
            get {
                object obj = ResourceManager.GetObject("stone_green_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_green_1 {
            get {
                object obj = ResourceManager.GetObject("stone_green_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_green_2 {
            get {
                object obj = ResourceManager.GetObject("stone_green_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_green_3 {
            get {
                object obj = ResourceManager.GetObject("stone_green_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_green_4 {
            get {
                object obj = ResourceManager.GetObject("stone_green_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_green_5 {
            get {
                object obj = ResourceManager.GetObject("stone_green_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 H 的本地化字符串。
        /// </summary>
        internal static string Stone_H {
            get {
                return ResourceManager.GetString("Stone_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I 的本地化字符串。
        /// </summary>
        internal static string Stone_I {
            get {
                return ResourceManager.GetString("Stone_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 J 的本地化字符串。
        /// </summary>
        internal static string Stone_J {
            get {
                return ResourceManager.GetString("Stone_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LV0 的本地化字符串。
        /// </summary>
        internal static string Stone_LV0 {
            get {
                return ResourceManager.GetString("Stone_LV0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LV1 的本地化字符串。
        /// </summary>
        internal static string Stone_LV1 {
            get {
                return ResourceManager.GetString("Stone_LV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LV2 的本地化字符串。
        /// </summary>
        internal static string Stone_LV2 {
            get {
                return ResourceManager.GetString("Stone_LV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LV3 的本地化字符串。
        /// </summary>
        internal static string Stone_LV3 {
            get {
                return ResourceManager.GetString("Stone_LV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LV4 的本地化字符串。
        /// </summary>
        internal static string Stone_LV4 {
            get {
                return ResourceManager.GetString("Stone_LV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LV5 的本地化字符串。
        /// </summary>
        internal static string Stone_LV5 {
            get {
                return ResourceManager.GetString("Stone_LV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橙色宝石 的本地化字符串。
        /// </summary>
        internal static string Stone_Orange {
            get {
                return ResourceManager.GetString("Stone_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_orange_0 {
            get {
                object obj = ResourceManager.GetObject("stone_orange_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_orange_1 {
            get {
                object obj = ResourceManager.GetObject("stone_orange_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_orange_2 {
            get {
                object obj = ResourceManager.GetObject("stone_orange_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_orange_3 {
            get {
                object obj = ResourceManager.GetObject("stone_orange_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_orange_4 {
            get {
                object obj = ResourceManager.GetObject("stone_orange_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_orange_5 {
            get {
                object obj = ResourceManager.GetObject("stone_orange_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 红色宝石 的本地化字符串。
        /// </summary>
        internal static string Stone_Red {
            get {
                return ResourceManager.GetString("Stone_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_red_0 {
            get {
                object obj = ResourceManager.GetObject("stone_red_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_red_1 {
            get {
                object obj = ResourceManager.GetObject("stone_red_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_red_2 {
            get {
                object obj = ResourceManager.GetObject("stone_red_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_red_3 {
            get {
                object obj = ResourceManager.GetObject("stone_red_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_red_4 {
            get {
                object obj = ResourceManager.GetObject("stone_red_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_red_5 {
            get {
                object obj = ResourceManager.GetObject("stone_red_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 特殊宝石 的本地化字符串。
        /// </summary>
        internal static string Stone_Special {
            get {
                return ResourceManager.GetString("Stone_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_special_1 {
            get {
                object obj = ResourceManager.GetObject("stone_special_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_special_2 {
            get {
                object obj = ResourceManager.GetObject("stone_special_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_special_3 {
            get {
                object obj = ResourceManager.GetObject("stone_special_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_special_4 {
            get {
                object obj = ResourceManager.GetObject("stone_special_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap stone_special_5 {
            get {
                object obj = ResourceManager.GetObject("stone_special_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 读取属性列表失败! 的本地化字符串。
        /// </summary>
        internal static string String_AttrListFailed {
            get {
                return ResourceManager.GetString("String_AttrListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通魔方 的本地化字符串。
        /// </summary>
        internal static string String_Basic {
            get {
                return ResourceManager.GetString("String_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 / 的本地化字符串。
        /// </summary>
        internal static string String_BetweenPages {
            get {
                return ResourceManager.GetString("String_BetweenPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string String_Error {
            get {
                return ResourceManager.GetString("String_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配装数据文件（*.itv）|*.itv 的本地化字符串。
        /// </summary>
        internal static string String_FileFormatDesc {
            get {
                return ResourceManager.GetString("String_FileFormatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金魔方 的本地化字符串。
        /// </summary>
        internal static string String_Gold {
            get {
                return ResourceManager.GetString("String_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取装备列表失败!
        ///是否手动指定游戏文件夹路径? 的本地化字符串。
        /// </summary>
        internal static string String_ItemListFailed {
            get {
                return ResourceManager.GetString("String_ItemListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取角色列表失败!
        ///无法使用配装功能！ 的本地化字符串。
        /// </summary>
        internal static string String_OccupationListFailed {
            get {
                return ResourceManager.GetString("String_OccupationListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取装备图片失败! 的本地化字符串。
        /// </summary>
        internal static string String_PicListFailed {
            get {
                return ResourceManager.GetString("String_PicListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  % 的本地化字符串。
        /// </summary>
        internal static string String_ProgressPercent {
            get {
                return ResourceManager.GetString("String_ProgressPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击道具图片
        ///查看同套道具 的本地化字符串。
        /// </summary>
        internal static string String_SetImage {
            get {
                return ResourceManager.GetString("String_SetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银魔方 的本地化字符串。
        /// </summary>
        internal static string String_Silver {
            get {
                return ResourceManager.GetString("String_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 × 的本地化字符串。
        /// </summary>
        internal static string String_X {
            get {
                return ResourceManager.GetString("String_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
